export const TOURNAMENT_LIST = "TOURNAMENT_LIST";
export const TOURNAMENT_WINNER_LIST = "TOURNAMENT_WINNER_LIST";
export const TOURNAMENT_CREATE = "TOURNAMENT_CREATE";
export const TOURNAMENT_STAGE = "TOURNAMENT_STAGE";
